### ISSUE TITLE
Any plans for generic retry from 1.18?

### ISSUE THREAD

**Issue by pzartem** [avast/retry-go#58]
I can implement it if you have any plan idea for it. This may reduce the amount of closure.

```go
type retryableFunc[TRes any] func() (TRes, error)

val, res := retry.Do(......
```

**Comment by JaSei** [comment]
Hi, I had thoughts about generics - but I only read this article https://planetscale.com/blog/generics-can-make-your-go-code-slower, and that doesn't sound like I want to add generics everywhere without a deeper analysis of value.

Have you please some another example where generic retry helps you?
Thanks

**Comment by pzartem** [comment]
Few issues with generics perf in that article are fixed only in 1.19. [Like this](https://github.com/golang/go/issues/50182)

The only one possible benefit with generics I see now is that you don't need an additional closure on result variable. It's not so much to implement it. 

Thanks!

**Comment by SladeThe** [comment]
1.19 is out. I vote up for this improvement.
Generics can really reduce amount of code around retryable calls.

**Comment by JaSei** [comment]
Please take a look at #91 and tell us what you think.
thank you

**Comment by zerkms** [comment]
It also is important to remember - that this suggestion only helps for functions that return one value. But functions could return 0, or more than 1 of them.

Counter suggestion: instead of changing `retry.Do` in a non-BC way, to introduce instead `retry.Do1`, `retry.Do2`, ... functions each of which returns the corresponding number of return values. Up to 5 should be fine, I guess.
